# Sistemas Inteligentes – Exercícios 1, 2 e 3

Este notebook mostra:
- **Exercício 1**: Indexing e slicing com o dataset *iris*.
- **Exercício 2**: Métodos `dropna`, `fillna` e `remove_by_index` da classe `Dataset`.
- **Exercício 3**: `SelectPercentile` aplicado ao *iris* usando `f_classification`.


# Exercício 1

In [17]:
from pathlib import Path
import numpy as np

from si.io.csv_file import read_csv
from si.data.dataset import Dataset
from si.feature_selection.select_percentile import SelectPercentile
from si.statistics.f_classification import f_classification

iris_path = Path(r"C:\Users\filip\OneDrive\Attachments\Ambiente de Trabalho\SIB_gh\si2\datasets\iris\iris.csv")
iris_ds = read_csv(iris_path, sep=",", features=True, label=True)

X, y = iris_ds.X, iris_ds.y
print("Shape X:", X.shape)
print("Classes:", np.unique(y, return_counts=True))
print("Features:", iris_ds.features)
print("Label name:", iris_ds.label)


Shape X: (150, 4)
Classes: (array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object), array([50, 50, 50]))
Features: Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width'], dtype='object')
Label name: class


**Exercício 1.2 – Penúltima variável independente**

In [18]:
penultima = X[:, -2]   # todas as linhas, penúltima coluna
print("Penúltima variável (primeiros 10 valores):", penultima[:10])
print("Dimensão:", penultima.shape)

Penúltima variável (primeiros 10 valores): [1.4 1.4 1.3 1.5 1.4 1.7 1.4 1.5 1.4 1.5]
Dimensão: (150,)


**Exercício 1.3 – Últimas 10 amostras e média por feature**

In [19]:
last10 = X[-10:, :]
mean_last10 = np.mean(last10, axis=0)

print("Últimas 10 amostras:\n", last10)
print("Média das últimas 10 amostras por feature:", mean_last10)

Últimas 10 amostras:
 [[6.7 3.1 5.6 2.4]
 [6.9 3.1 5.1 2.3]
 [5.8 2.7 5.1 1.9]
 [6.8 3.2 5.9 2.3]
 [6.7 3.3 5.7 2.5]
 [6.7 3.  5.2 2.3]
 [6.3 2.5 5.  1.9]
 [6.5 3.  5.2 2. ]
 [6.2 3.4 5.4 2.3]
 [5.9 3.  5.1 1.8]]
Média das últimas 10 amostras por feature: [6.45 3.03 5.33 2.17]


**Exercício 1.4 – Amostras com todas as features <= 6**

In [20]:
mask_less6 = np.all(X <= 6, axis=1)
num_less6 = np.sum(mask_less6)

print("Número de amostras com todas as features <= 6:", num_less6)

Número de amostras com todas as features <= 6: 89


**Exercício 1.5 – Amostras com label != 'Iris-setosa'**

In [21]:
mask_not_setosa = (y != "Iris-setosa")
num_not_setosa = np.sum(mask_not_setosa)

print("Número de amostras com label != 'Iris-setosa':", num_not_setosa)

Número de amostras com label != 'Iris-setosa': 100


# Exercício 2

In [22]:
from si.data.dataset import Dataset
import numpy as np

X_demo = np.array([
    [1.0, 2.0],
    [np.nan, 3.0],
    [4.0, np.nan],
    [5.0, 6.0]
])
y_demo = np.array([0, 1, 1, 0])

demo_ds = Dataset(X=X_demo.copy(), y=y_demo.copy(), features=["f1", "f2"], label="class")
print("Dataset de exemplo (com NaNs):\n", demo_ds.X)


Dataset de exemplo (com NaNs):
 [[ 1.  2.]
 [nan  3.]
 [ 4. nan]
 [ 5.  6.]]


**Exercício 2 – fillna com média**

In [23]:
demo_fill = Dataset(
    X=X_demo.copy(),
    y=y_demo.copy(),
    features=["f1", "f2"],
    label="class"
)

demo_fill.fillna("mean")
print("Depois de fillna('mean'):\n", demo_fill.X)

Depois de fillna('mean'):
 [[1.         2.        ]
 [3.33333333 3.        ]
 [4.         3.66666667]
 [5.         6.        ]]


**Exercício 2 – dropna**

In [24]:
demo_drop = Dataset(
    X=X_demo.copy(),
    y=y_demo.copy(),
    features=["f1", "f2"],
    label="class"
)

demo_drop.dropna()
print("Depois de dropna():")
print("X:\n", demo_drop.X)
print("y:", demo_drop.y)

Depois de dropna():
X:
 [[1. 2.]
 [5. 6.]]
y: [0 0]


**Exercício 2 – remove_by_index**

In [25]:
demo_rm = Dataset(
    X=X_demo.copy(),
    y=y_demo.copy(),
    features=["f1", "f2"],
    label="class"
)

demo_rm.remove_by_index([1, 2])
print("Depois de remover índices [1, 2]:")
print("X:\n", demo_rm.X)
print("y:", demo_rm.y)

Depois de remover índices [1, 2]:
X:
 [[1. 2.]
 [5. 6.]]
y: [0 0]


# Exercício 3

**Exercício 3 – SelectPercentile com f_classification no iris**

In [26]:
selector = SelectPercentile(score_func=f_classification, percentile=50)  
selector.fit(iris_ds)
iris_reduced = selector.transform(iris_ds)

print("Shape original:", iris_ds.X.shape)
print("Shape reduzido:", iris_reduced.X.shape)
print("Features selecionadas:", iris_reduced.features)

Shape original: (150, 4)
Shape reduzido: (150, 2)
Features selecionadas: ['petal_length', 'petal_width']
